# Generated by Selenium IDE
from base_test import get_driver_with_session, is_logged_in
from selenium.webdriver.common.by import By
from utils import wait_element
import time

class TestCPFINS059():
  def setup_method(self, driver):
    driver = get_driver_with_session()

    if not is_logged_in(driver):
        print("Por favor inicia sesión manualmente.")
        input("Presiona Enter una vez hayas iniciado sesión...")

    self.driver = driver
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_cPFINS059(self):
    self.driver.get("https://teammates-hormiga-1.uc.r.appspot.com/")
    wait_element(self.driver, By.CSS_SELECTOR, ".nav-item:nth-child(1) > .dropdown-toggle").click()
    wait_element(self.driver, By.LINK_TEXT, "To instructor pages").click()
    wait_element(self.driver, By.LINK_TEXT, "Sessions").click()
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .ng-star-inserted > .ng-star-inserted .ng-star-inserted > .btn").click()
    self.driver.execute_script("window.scrollTo(0,1730.8609619140625)")
    self.driver.execute_script("window.scrollTo(0,5470.728515625)")
    wait_element(self.driver, By.ID, "btn-new-question").click()
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(4) > .d-flex > .dropdown-item").click()
    self.driver.execute_script("window.scrollTo(0,5993.642578125)")
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-11 #question-brief").click()
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-11 #question-brief").send_keys("¿Con qué frecuencia contribuye el estudiante en las discusiones de equipo?")
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-11 input[type=\"text\"]").send_keys("Opción 1")
    wait_element(self.driver, By.ID, "btn-save-new").click()

    time.sleep(1)
    self.driver.save_screenshot('screenshots/CPFINS062.png')
