# Generated by Selenium IDE
from base_test import get_driver_with_session, is_logged_in
from selenium.webdriver.common.by import By
from utils import wait_element
import time

class TestCPFINS058():

  def setup_method(self, driver):
    driver = get_driver_with_session()

    if not is_logged_in(driver):
        print("Por favor inicia sesión manualmente.")
        input("Presiona Enter una vez hayas iniciado sesión...")

    self.driver = driver
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_cPFINS058(self):
    self.driver.get("https://teammates-hormiga-1.uc.r.appspot.com/web/instructor/home")
    elemento = wait_element(self.driver, By.LINK_TEXT, "Sessions")
    elemento.click()
    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .ng-star-inserted > .ng-star-inserted .ng-star-inserted > .btn")
    elemento.click()
    self.driver.execute_script("window.scrollTo(0,1730.8609619140625)")
    self.driver.execute_script("window.scrollTo(0,5470.728515625)")
    elemento = wait_element(self.driver, By.ID, "btn-new-question")
    elemento.click()
    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(4) > .d-flex > .dropdown-item")
    elemento.click()
    self.driver.execute_script("window.scrollTo(0,5993.642578125)")
    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-10 #question-brief")
    elemento.click()
    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-10 #question-brief").send_keys("¿Con qué frecuencia contribuye el estudiante en las discusiones de equipo?")

    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".ng-tns-c2803763673-10 .row:nth-child(2) > .col-md-2")
    elemento.click()
    elemento = wait_element(self.driver, By.CSS_SELECTOR, ".cdk-drag:nth-child(1) .input-group-btn span")
    elemento.click()

    time.sleep(1)
    self.driver.save_screenshot('screenshots/CPFINS062.png')
