# Generated by Selenium IDE
from base_test import get_driver_with_session, is_logged_in
from selenium.webdriver.common.by import By
from utils import wait_element
import time

class TestCPFINS063():
  def setup_method(self):
    driver = get_driver_with_session()

    if not is_logged_in(driver):
        print("Por favor inicia sesión manualmente.")
        input("Presiona Enter una vez hayas iniciado sesión...")

    self.driver = driver
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_cPFINS063(self):
    self.driver.get("https://teammates-hormiga-1.uc.r.appspot.com/")
    wait_element(self.driver, By.CSS_SELECTOR, ".nav-item:nth-child(1) > .dropdown-toggle").click()
    wait_element(self.driver, By.LINK_TEXT, "To instructor pages").click()
    wait_element(self.driver, By.LINK_TEXT, "Sessions").click()
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(2) > .ng-star-inserted > .ng-star-inserted .ng-star-inserted > .btn").click()
    wait_element(self.driver, By.ID, "btn-new-question").click()
    wait_element(self.driver, By.CSS_SELECTOR, ".ng-star-inserted:nth-child(7) > .d-flex > .dropdown-item").click()
    self.driver.execute_script("window.scrollTo(0,6160.52978515625)")
    wait_element(self.driver, By.CSS_SELECTOR, "#question-brief:not([disabled])").send_keys("¿Con qué frecuencia contribuye el estudiante en las discusiones de equipo?")
    wait_element(self.driver, By.CSS_SELECTOR, ".cdk-drag:nth-child(1) .form-control:not([disabled])").send_keys("Opción 1")
    wait_element(self.driver, By.CSS_SELECTOR, ".cdk-drag:nth-child(2) .form-control:not([disabled])").send_keys("Opción 2")
    wait_element(self.driver, By.CSS_SELECTOR, "#total-points:not([disabled])").clear()
    wait_element(self.driver, By.CSS_SELECTOR, "#total-points:not([disabled])").send_keys("0")
    wait_element(self.driver, By.ID, "btn-save-new").click()

    time.sleep(1)
    self.driver.save_screenshot('screenshots/CPFINS063.png')

